<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: kunkel
 * Date: Fri, 21 Dec 2018 17:13:07 +0000
 */

$conf['title'] = 'HPC Certification Forum';
$conf['start'] = 'b';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useheading'] = 'navigation';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['plugin']['captcha']['loginprotect'] = 1;
$conf['plugin']['captcha']['question'] = 'What is blue and like the sky? ';
$conf['plugin']['captcha']['answer'] = 'sky';
$conf['plugin']['indexmenu']['skip_index'] = '/(wiki|playground)/';
$conf['plugin']['indexmenu']['skip_file'] = '/^(cookiebanner|bibtex|impressum|privacy|sidebar)$/';

// end auto-generated content
