<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sat, 17 Nov 2018 20:43:34 +0000
 */

$conf['title'] = 'HPC Certification Forum';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['userewrite'] = '1';
$conf['plugin']['indexmenu']['skip_index'] = '/(wiki|playground)/';
$conf['plugin']['indexmenu']['skip_file'] = '/^(cookiebanner|bibtex|impressum|privacy|sidebar)$/';

// end auto-generated content
